<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Mk8.Sava.Transport</AssemblyName>
    <RootNamespace>Mk8.Sava</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Mk8.Sava.Contracts/Mk8.Sava.Contracts.csproj" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
