<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Mk8.Sava.INF</AssemblyName>
    <RootNamespace>Mk8.Sava</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.14.2" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Mk8.Sava.Contracts/Mk8.Sava.Contracts.csproj" />
    <ProjectReference Include="../Mk8.Sava.DAL/Mk8.Sava.DAL.csproj" />
  </ItemGroup>
</Project>
